import 'dart:typed_data';

import 'package:bencode_dart/bencode_dart.dart' as bencoder;
import 'package:dartorrent_common/dartorrent_common.dart';

import '../kademlia/node.dart';

/// A KRPC message is a single dictionary with three keys common to every message
/// and additional keys depending on the type of message.
///
/// Every message has a key "t" with a string value representing a transaction ID.
/// This transaction ID is generated by the querying node and is echoed in the response,
/// so responses may be correlated with multiple queries to the same node.
/// The transaction ID should be encoded as a short string of binary numbers, typically
///  2 characters are enough as they cover 2^16 outstanding queries.
///
/// Every message also has a key "y" with a single character value describing the type
/// of message. The value of the "y" key is one of "q" for query, "r" for response,
/// or "e" for error.
///
/// A key "v" should be included in every message with a client version string.
/// The string should be a two character client identifier registered in
/// [BEP 20](http://www.bittorrent.org/beps/bep_0020.html)
/// followed by a two character version identifier.
///

const transactionKey = 't';
const methodKey = 'y';
const queryKey = 'q';
const responseKey = 'r';
const errorKey = 'e';
const argumentsKey = 'a';
const idKey = 'id';
const targetKey = 'target';
const nodesKey = 'nodes';
const valuesKey = 'values';
const infoHashKey = 'info_hash';
const tokenKey = 'token';

const methodPing = 'ping';
const methodFindNode = 'find_node';
const methodGetPeers = 'get_peers';
const methodAnnouncePeer = 'announce_peer';

const queryKeys = [methodPing, methodFindNode, methodGetPeers];

/// [transactionId] should be encoded as a short string of binary numbers, typically
///  2 characters are enough as they cover 2^16 outstanding queries.
Uint8List? queryMessage(String transactionId, String method, Map arguments) {
  assert(transactionId.length == 2, 'Transaction ID length should be 2');
  var message = {
    transactionKey: transactionId,
    methodKey: queryKey,
    queryKey: method,
    argumentsKey: arguments
  };
  return bencoder.encode(message);
}

Uint8List? responseMessage(String transactionId, Map response) {
  var message = {
    transactionKey: transactionId,
    methodKey: responseKey,
    responseKey: response
  };
  return bencoder.encode(message);
}

/// `error = {"t":"aa", "y":"e", "e":[201, "A Generic Error Ocurred"]}`
Uint8List? errorMessage(String transactionId, int code, String errorMsg) {
  var message = {
    transactionKey: transactionId,
    methodKey: errorKey,
    errorKey: [code, errorMsg]
  };
  return bencoder.encode(message);
}

/// `Ping` method query message.
///
///  arguments:  `{"id" : "<querying nodes id>"}`
///
/// [nodeId] is 20 length string,[transactionId] is 2 length string
Uint8List? pingMessage(String transactionId, String nodeId) {
  return queryMessage(transactionId, methodPing, {idKey: nodeId});
}

/// `response: {"id" : "<queried nodes id>"}`
Uint8List? pongMessage(String transactionId, String nodeId) {
  return responseMessage(transactionId, {idKey: nodeId});
}

/// `arguments:  {"id" : "<querying nodes id>", "target" : "<id of target node>"}`
Uint8List? findNodeMessage(
    String transactionId, String nodeId, String targetId) {
  return queryMessage(
      transactionId, methodFindNode, {idKey: nodeId, targetKey: targetId});
}

/// `response: {"id" : "<queried nodes id>", "nodes" : "<compact node info>"}`
///
/// Contact information for nodes is encoded as a 26-byte string.
/// Also known as "Compact node info" the 20-byte Node ID in network byte order
/// has the compact IP-address/port info concatenated to the end.
Uint8List? findNodeResponse(
    String transactionId, String nodeId, Iterable<Node>? nodes) {
  if (nodes == null) {
    return null;
  }
  var nodesStr = nodes.fold('', (previousValue, node) {
    return '$previousValue${node.toContactEncodingString()}';
  });
  return responseMessage(transactionId, {idKey: nodeId, nodesKey: nodesStr});
}

/// `arguments:  {"id" : "<querying nodes id>", "info_hash" : "<20-byte infohash of target torrent>"}`
Uint8List? getPeersMessage(
    String transactionId, String nodeId, String infoHash) {
  return queryMessage(
      transactionId, methodGetPeers, {idKey: nodeId, infoHashKey: infoHash});
}

/// response : `{"id" : "<queried nodes id>", "token" :"<opaque write token>", "values" : ["<peer 1 info string>", "<peer 2 info string>"],"nodes" : "<compact node info>"}`
Uint8List? getPeersResponse(String transactionId, String nodeId, String token,
    {Iterable<Node>? nodes, Iterable<CompactAddress>? peers}) {
  String? nodesStr;
  if (nodes != null && nodes.isNotEmpty) {
    nodesStr = nodes.fold('', (previousValue, node) {
      return '$previousValue${node.toContactEncodingString()}';
    });
  }
  List<String?>? values;
  if (peers != null && peers.isNotEmpty) {
    values = <String?>[];
    for (var peer in peers) {
      values.add(peer.toContactEncodingString());
    }
  }
  var r = <String, dynamic>{idKey: nodeId, 'token': token};
  if (nodesStr != null) {
    r[nodesKey] = nodesStr;
  }
  if (values != null) {
    r[valuesKey] = values;
  }
  return responseMessage(transactionId, r);
}

/*
arguments:  {"id" : "<querying nodes id>",
  "implied_port": <0 or 1>,
  "info_hash" : "<20-byte infohash of target torrent>",
  "port" : <port number>,
  "token" : "<opaque token>"} 
*/
Uint8List? announcePeerMessage(String transactionId, String nodeId,
    String infoHash, int port, String token,
    [bool impliedPort = true]) {
  return queryMessage(transactionId, methodAnnouncePeer, {
    'implied_port': impliedPort ? 1 : 0,
    idKey: nodeId,
    infoHashKey: infoHash,
    'port': port,
    tokenKey: token
  });
}

/// `response: {"id" : "<queried nodes id>"}`
Uint8List? announcePeerResponse(String transactionId, String nodeId) {
  return responseMessage(transactionId, {idKey: nodeId});
}
